queue_rules:
  - name: shared_queue
    conditions:
      - "#approved-reviews-by>=1"

pull_request_rules:
  - name: automatic merge of 🚑 hotfix (high priority)
    conditions:
      - "#approved-reviews-by>=1"
      - label=A-bug
    actions:
      queue:
        name: shared_queue
        method: merge
        
  - name: automatic merge squash on website/docs(low priority)
    conditions:
      - "#approved-reviews-by>=1"
      - -files~=^(!?website/)
    actions:
      queue:
        name: shared_queue
        method: squash

  - name: put other pr to merge queue
    conditions:
      - "#approved-reviews-by>=1"
      - label!=A-bug
    actions:
      queue:
        name: shared_queue
        method: squash
        
# if there is a conflict in a approved PR, ping the author.
  - name: ping author if there is conflicts
    conditions:
      - conflict
      - "#approved-reviews-by >= 1"
    actions:
      comment:
        message: |
          This pull request has merge conflicts, you should resolve it before merged. @{{author}} please update it :)

          Try `@mergify update` or update manually.

  - name: Welcome new contributor
    conditions:
      - author!=Mergify
    actions:
      comment:
        message: |
          Thanks for the contribution!
          I have applied any labels matching special text in your PR Changelog.

          Please review the labels and make any necessary changes.

  - name: label on new feature
    conditions:
      - body~=(?m)^\[X\] New Feature
    actions:
      label:
        add:
          - PR-feature
  - name: label on bug fix
    conditions:
      - body~=(?m)^\[X\] Bug Fix
    actions:
      label:
        add:
          - PR-bug
  - name: label on Documentation
    conditions:
      - body~=(?m)^\[X\] Documentation
    actions:
      label:
        add:
          - PR-docs
